export const nusResidences: String[] = [
  "Eusoff Hall",
  "Kent Ridge Hall",
  "King Edward VII Hall",
  "Raffles Hall",
  "Sheares Hall",
  "Temasek Hall",
  "CAPT",
  "RC4",
  "Ridge View RC",
  "Tembusu College",
  "Cinnamon Wing",
  "West Wing",
];

export const ntuResidences: String[] = [
  "Crescent Hall",
  "Pioneer Hall",
  "Binjai Hall",
  "Tanjong Hall",
  "Banyan Hall",
  "Saraca Hall",
  "Tamarind Hall",
  "Hall1",
  "Hall2",
  "Hall3",
  "Hall4",
  "Hall5",
  "Hall6",
  "Hall7",
  "Hall8",
  "Hall9",
  "Hall10",
  "Hall11",
  "Hall12",
  "Hall13",
  "Hall14",
  "Hall15",
  "Hall16",
];

export const smuResidences: String[] = [
  "Prinsep Street Residences",
  "yo:Ha Hostel",
];
